### ISSUE TITLE
Install fails with ember-cli 2.15.1 and yarn

### ISSUE THREAD

**Issue by BryanHunt** [danielspaniel/ember-data-change-tracker#27]
```
ember install ember-data-change-tracker
Command failed: yarn add --dev ember-data-change-tracker --non-interactive
warning ember-truth-helpers@1.2.0: The engine "ember-cli-app-version" appears to be invalid.
error ember-cli-babel@6.0.0: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.*".
error Found incompatible module

yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Error: Command failed: yarn add --dev ember-data-change-tracker --non-interactive
warning ember-truth-helpers@1.2.0: The engine "ember-cli-app-version" appears to be invalid.
error ember-cli-babel@6.0.0: The engine "node" is incompatible with this module. Expected version "^4.5 || 6.* || 7.*".
error Found incompatible module

yarn add v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

    at Promise.all.then.arr (/Users/bhunt/Nvidia/Code/NVProjectPlanUI/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by humanchimp** [comment]
i found the `yarn --ignore-engines` to be a serviceable workaround

**Comment by jpsirois** [comment]
This will be fixed by b82b01159a3b065ab686f5f74e1a83df2048aacd but it’s still not released.

**Comment by danielspaniel** [comment]
v 0.6.3. is now released .. so let me know if this issue is fixed

**Comment by jpsirois** [comment]
Yeah it fixed the issue! Thanks!

**Comment by danielspaniel** [comment]
no problem .. sorry for delay .. was in a fog there for a while
